# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41969f434423778937a1d72a7c64cb168d50ca384bfc7898537cfe61945e9472ba83df0886d006c38ef9f15e605910782006d15d2f7a9d73c7cad0f069a7003f

test:
  secret_key_base: ba56f8aff5752678660f5c56f70e8d895e773b052da488c3cc00723e492567634886f35083a008295cc5914d60358a644948fdadcccc25c6c0e120b8f8667261

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: cebed76912423d9e00fe3259d1cb2087a23312f7bb475342c9f9b277b9fe956dbc85a42d97247feb2accd92b32bf5f2b5b5447f86629af53d7bde521fed17a6a

